### ISSUE TITLE
Projet en commun

### ISSUE THREAD

**Issue by moussadiallo** [adamacoly/adamacoly#1]
Si c'est un projet en commun vous pouvez demander à Sokhna Bousso de vous inviter sur son repo et vous travaillez ensemble en vous partageant les tâches. Sachez que si vous êtes à 2 sur le projet je vais vous demander plus de choses que les autres

**Comment by adamacoly** [comment]
bonsoir monsieur. j ai essayer de faire un push et j'ai eu cette erreur "remote: Permission to adamacoly/templateHTML.git denied to sokhnaawa19. 
fatal: unable to access 'https://github.com/adamacoly/templateHTML.git/': The requested URL returned error: 403"
sokhna awa a utilisé ma machine pour faire un push et sa a enregistré son id et son mdp je voudrai savoir comment changer cela.
